version: 0.2

phases:
  pre_build:
    commands:
      - echo Set up Docker login...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 498794313379.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build Docker image...
      - cd analytics
      - docker build -t coworking .
      - docker tag coworking:latest 498794313379.dkr.ecr.us-east-1.amazonaws.com/hient4-coworking:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo Push the image to your Amazon ECR account...
      - docker push 498794313379.dkr.ecr.us-east-1.amazonaws.com/hient4-coworking:$CODEBUILD_BUILD_NUMBER